ajout mvc
azuera/patefinder pull request #35
Opened 2023-05-23 14:01 UTC by azuera

2023-05-23 14:02 UTC, MathiasDAHA approved these changes

2023-05-23 14:24 UTC, Dreeckan requested changes

2023-05-23 14:24 UTC, Dreeckan commented on Includes/pages.php
> +    'createCharacterSheet'=>CreateCharacterSheetController::class,
ça manque un peu d'espaces autour des `=>` tout ça :P

2023-05-23 14:24 UTC, Dreeckan commented on src/Controller/CharacterListController.php
> +        <?php
Il vaut mieux éviter de garder ces fermetures / ouvertures de PHP au milieu d'une classe (c'est pas très PSR ;) )

2023-05-23 14:24 UTC, Dreeckan commented on src/Controller/CharacterSheetController.php
> +        if (isset($_GET)) {
$_GET est toujours définie. Est-ce que vous vouliez vérifier si elle était vide ?

2023-05-23 14:24 UTC, Dreeckan commented on src/Controller/CharacterSheetController.php
> +            'id'=>$id,
Un peu d'espace autour des => ?

2023-05-24 07:19 UTC, azuera commented on src/Controller/CharacterSheetController.php
> +        if (isset($_GET)) {
oui

2023-05-24 08:42 UTC, Vlndo approved these changes
![Knuckles_APPROVED](https://github.com/azuera/patefinder/assets/107538197/db5b2b52-5a9f-445c-bae6-1a0c96b69ad4)

2023-05-24 08:43 UTC, RealHich69 approved these changes

2023-05-24 08:53 UTC, Dreeckan commented on Includes/pages.php
> +    'createCharacterSheet'=>CreateCharacterSheetController::class,
Ils sont où mes espaces ? :O

2023-05-24 13:08 UTC, merged